// Generated by CoffeeScript 1.9.3
(function() {
  var gulp, program, task;

  program = require('commander');

  program.on('--help', function() {
    console.log('  Usage:');
    console.log();
    console.log('    $', 'webpack-tool run server', '启动测试服务器');
    console.log('    $', 'webpack-tool run build', ' 生成最终构建文件');
    console.log();
  });

  program.parse(process.argv);

  task = program.args[0];

  if (!task) {
    program.help();
  } else {
    gulp = require('gulp');
    require('./gulpfile');
    gulp.start(task);
  }

}).call(this);
