// Generated by CoffeeScript 1.9.3
(function() {
  var _, webpack, webpackDevConfig;

  webpack = require('webpack');

  webpackDevConfig = require('./configs/webpack.config');

  _ = require('lodash');

  module.exports = function(opts, mode) {
    var webpackDevCompiler;
    opts = _.cloneDeep(opts);
    return webpackDevCompiler = webpack(webpackDevConfig(opts, mode));
  };

}).call(this);
