// Generated by CoffeeScript 1.9.3
(function() {
  var karmaServer;

  karmaServer = require('karma').Server;

  module.exports = function(callback) {
    return new karmaServer({
      configFile: __dirname + '/configs/karma.conf',
      singleRun: false
    }, callback);
  };

}).call(this);
