// Generated by CoffeeScript 1.9.3
(function() {
  var _, options, path, version;

  path = require('path');

  version = '1.0.0';

  _ = require('lodash');

  options = {
    name: 'webpack-app',
    version: version,
    env: 'development',
    projectDir: path.join(__dirname),
    cdnPath: '/',
    server: {
      devPort: 3210,
      webPort: 3200,
      entry: path.join(__dirname, './dist/1.0.0'),
      publicPath: '/',
      liveload: true
    },
    webpack: {
      base: {
        webpackDebug: false,
        configFile: true,
        commonFiles: true,
        base64Limit: null,
        cdn: false,
        cache: true,
        debug: true,
        recursive: true,
        exportCss: true,
        exportHtml: true,
        hot: false,
        entry: path.join(__dirname, './src/js/pages'),
        output: path.join(__dirname, './dist', version),
        htmls: path.join(__dirname, './src/htmls'),
        loaders: [],
        resolve: {
          root: path.resolve(__dirname),
          alias: {},
          extensions: [],
          modulesDirectories: ['node_modules']
        },
        externals: {}
      },
      development: {
        hash: false,
        uglify: false,
        sourceMap: true,
        map: true
      },
      qa: {
        hash: true,
        uglify: true,
        sourceMap: true,
        map: true
      },
      production: {
        hash: true,
        uglify: true,
        sourceMap: false,
        map: true
      },
      prebuilt: {
        hash: false,
        uglify: true,
        sourceMap: false,
        map: false
      }
    },
    config: {}
  };

  module.exports = _.cloneDeep(options);

}).call(this);
