// Generated by CoffeeScript 1.9.3
(function() {
  var _, cwd, devConfig, error, extend, localConfig, path, pkg;

  path = require('path');

  cwd = process.cwd();

  pkg = require(path.join(cwd, 'package.json'));

  _ = require('lodash');

  extend = function(object, properties) {
    var key, val;
    for (key in properties) {
      val = properties[key];
      object[key] = val;
    }
    return object;
  };

  try {
    localConfig = require(path.join(cwd, 'dev.conf.js'));
    pkg = extend(pkg, localConfig);
  } catch (_error) {
    error = _error;
  }

  pkg.buildConfig.output = pkg.buildConfig.output.replace('__version__', pkg.version);

  devConfig = {};

  devConfig.name = pkg.name || "webpack-tool";

  devConfig.version = pkg.version || "1.0.0";

  devConfig.env = (pkg.projectConfig && pkg.projectConfig.env) || "development";

  devConfig.config = pkg.projectConfig;

  devConfig.server = pkg.serverConfig;

  devConfig.webpack = {
    base: pkg.buildConfig || {}
  };

  if (pkg.developmentBuildConfig) {
    devConfig.webpack.development = pkg.developmentBuildConfig || {};
  }

  if (pkg.qaBuildConfig) {
    devConfig.webpack.qa = pkg.qaBuildConfig || {};
  }

  if (pkg.productionBuildConfig) {
    devConfig.webpack.production = pkg.productionBuildConfig || {};
  }

  devConfig.npmDependencies = pkg.devDependencies;

  module.exports = _.cloneDeep(devConfig);

}).call(this);
