// Generated by CoffeeScript 1.9.3
(function() {
  var assign, cwd, defaultConfig, env, getLoaders, gutil, loaders, opts, path, webpackConfig, webpackDevConfig, webpackTool;

  assign = require('object-assign');

  webpackDevConfig = require('./webpack.config');

  opts = require('./dev.config');

  webpackTool = require('../../index');

  getLoaders = require('../configs/getloaders');

  gutil = require('gulp-util');

  defaultConfig = require('./default.config.js');

  path = require('path');

  cwd = process.cwd();

  loaders = getLoaders(opts);

  env = gutil.env.env || opts.env;

  webpackConfig = assign(defaultConfig.webpack.base, opts.webpack.base, opts.webpack[env] ? opts.webpack[env] : defaultConfig.webpack[env]);

  module.exports = function(config) {
    var preprocessors, settings;
    preprocessors = {};
    preprocessors[cwd + '/_test/*'] = ['webpack', 'sourcemap'];
    settings = {
      basePath: '',
      frameworks: ['mocha'],
      files: [path.join(cwd, '_test/index.js')],
      preprocessors: preprocessors,
      webpack: {
        devtool: 'inline-source-map',
        resolve: webpackConfig.resolve,
        module: {
          loaders: loaders
        }
      },
      webpackMiddleware: {
        noInfo: true,
        stats: {
          colors: true
        }
      },
      reporters: ['spec'],
      port: 9876,
      colors: true,
      logLevel: config.LOG_INFO,
      autoWatch: true,
      browsers: ['Chrome'],
      captureTimeout: 60000,
      singleRun: false,
      plugins: [require("karma-webpack"), require("karma-mocha"), require("karma-spec-reporter"), require("karma-chrome-launcher"), require("karma-sourcemap-loader")]
    };
    return config.set(settings);
  };

}).call(this);
