// Generated by CoffeeScript 1.9.3
(function() {
  var _, cwd, devConfig, error, extend, localConfig, path, pkg;

  path = require('path');

  cwd = process.cwd();

  pkg = require(path.join(cwd, 'package.json'));

  _ = require('lodash');

  extend = function(object, properties) {
    var key, val;
    for (key in properties) {
      val = properties[key];
      object[key] = val;
    }
    return object;
  };

  try {
    localConfig = require(path.join(cwd, 'dev.conf.js'));
    pkg = extend(pkg, localConfig);
  } catch (_error) {
    error = _error;
  }

  pkg.buildConfig.output = pkg.buildConfig.output.replace('__version__', pkg.version);

  pkg.buildConfig.jsPath = pkg.buildConfig.prebuiltJsPath;

  pkg.buildConfig.cssPath = pkg.buildConfig.prebuiltCssPath;

  pkg.buildConfig.htmlPath = pkg.buildConfig.prebuiltHtmlPath;

  pkg.buildConfig.configFile = false;

  pkg.buildConfig.commonFiles = false;

  devConfig = {};

  devConfig.name = pkg.name || "webpack-tool";

  devConfig.version = pkg.version || "1.0.0";

  devConfig.env = "prebuilt";

  devConfig.config = pkg.projectConfig;

  devConfig.server = pkg.serverConfig;

  devConfig.webpack = {
    base: pkg.buildConfig || {}
  };

  devConfig.webpack.production = pkg.prebuiltConfig || {};

  devConfig.npmDependencies = pkg.devDependencies;

  module.exports = _.cloneDeep(devConfig);

}).call(this);
